[theme]
primaryColor = "#0D9488"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172B4D"
font = "sans serif"

[server]
maxUploadSize = 100

[browser]
gatherUsageStats = false

